# Generated by Django 5.0.1 on 2024-05-10 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='registered_users',
            field=models.ManyToManyField(related_name='registered_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
